### PR TITLE
Added forest compact check in CI

### LINKED ISSUE #69: Automate Forest compat check
To check if the changes to this repository work fine with Forest, one has to check it manually. Let's automate it.

Potential steps:
1. Have `forest` as a submodule - the commit of this must be checked, we don't want fiascoes from Forest to propagate into `fil-actor-states`.
2. Create a test rule to the Makefile, inside:
   * fetch the submodule, init, recurse
   * with `sed` change the paths in the Forest workspace Cargo file to use local `fil-actor-states`
   * run `make build test-all`
   * run this script https://github.com/ChainSafe/forest/blob/main/scripts/calibnet_health_check.sh - adding the wallet key to the repo's secrets will be required.
3. Run this rule in the CI workflow

### PR DESCRIPTION
**Pull request by sudo-shashank**
**Summary of changes**
Changes introduced in this pull request:
- Added `forest` as submodule
- Automated `forest` build, test and calibnet sync check

**Reference issue to close (if applicable)**

Closes #69 

**Other information and links**

### CODE REVIEW

**Comment by lemmih** [comment]
I added the `CALIBNET_WALLET` secret to this repository.

**Review by lemmih — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
@sudo-shashank Could you please point me to where are Forest unit and component tests invoked?

**Comment by LesnyRumcajs** [comment]
> > @sudo-shashank Could you please point me to where are Forest unit and component tests invoked?
> 
> I don't think any of the Forest unit tests touch the fil-actor-interface.

Off the top of my head, `config dump` cli tests do use `Policy` unless something changed. I recall adding a test that uses Cids for v10 actors, though probably it's still hardcoded there (it shouldn't be).

If we don't want them, there's no point in installing nextest, though I believe those are useful.

**Comment by lemmih** [comment]
> > > @sudo-shashank Could you please point me to where are Forest unit and component tests invoked?
> > 
> > 
> > I don't think any of the Forest unit tests touch the fil-actor-interface.
> 
> Off the top of my head, `config dump` cli tests do use `Policy` unless something changed. I recall adding a test that uses Cids for v10 actors, though probably it's still hardcoded there (it shouldn't be).
> 
> If we don't want them, there's no point in installing nextest, though I believe those are useful.

Running all the unit tests takes more than 40 minutes on GitHub. I'll see if we can get buildjet for this repository.

**Review by lemmih — APPROVED** [review]

**Pull request merged**
