### PR TITLE
Prepare release for V7.0.0-rc.1

### PR DESCRIPTION
**Pull request by sudo-shashank**
**Summary of changes**
Changes introduced in this pull request:
- Update version

**Reference issue to close (if applicable)**

Closes 

**Other information and links**

### CODE REVIEW

**Review by lemmih — APPROVED** [review]

**Comment by LesnyRumcajs** [comment]
Shouldn't the versions be `7.0.0-rc.1`?

**Comment by sudo-shashank** [comment]
> Shouldn't the versions be `7.0.0-rc.1`?

version follows `major.minor.patch` format only, the release tag will be marked as `v7.0.0-rc.1`

**Comment by LesnyRumcajs** [comment]
> > Shouldn't the versions be `7.0.0-rc.1`?
> 
> version follows `major.minor.patch` format only, the release tag will be marked as `v7.0.0-rc.1`

Why does it have to follow this format? For example, in ref-fvm one can add an extra suffix. See https://github.com/filecoin-project/ref-fvm/blob/e9044cb8eca4ca928bede06689c4408b7837cc6f/sdk/Cargo.toml#L4

Will the release on crates.io follow the git tag?

**Comment by sudo-shashank** [comment]
> > > Shouldn't the versions be `7.0.0-rc.1`?
> > 
> > 
> > version follows `major.minor.patch` format only, the release tag will be marked as `v7.0.0-rc.1`
> 
> Why does it have to follow this format? For example, in ref-fvm one can add an extra suffix. See https://github.com/filecoin-project/ref-fvm/blob/e9044cb8eca4ca928bede06689c4408b7837cc6f/sdk/Cargo.toml#L4
> 
> Will the release on crates.io follow the git tag?

corrected

**Review by LesnyRumcajs — APPROVED** [review]

**Pull request merged**
