### PR TITLE
Remove unused code

### LINKED ISSUE #22: Remove dead code
There is some dead code in the actor interface. It includes:
- `load_actor_state`
- `is_miner_actor`

Find all the dead code and remove it.

### PR DESCRIPTION
**Pull request by sudo-shashank**
**Summary of changes**
Changes introduced in this pull request:
Remove unused code from:
- [X] Account
- [X] Cron
- [X] Datacap
- [X] Eam
- [X] Ethaccount
- [X] Evm
- [X] Fil actor interface
- [X] Init
- [X] Market
- [X] Miner
- [X] Multisig
- [X] Paych
- [X] Power
- [X] Reward
- [X] Runtime
- [X] System
- [X] Verifreg

**Reference issue to close (if applicable)**

Closes #22 

**Other information and links**

### CODE REVIEW

**Review by lemmih — CHANGES_REQUESTED** [review]
Some of these methods are used in Forest. Try to only delete the methods that are not used in Forest.

A lot of other things are still unused:

- Almost everything in: runtime_v10/src/builtin/shared.rs
- The `test_utils` is unused in `runtime_v10`
- The `js` feature is unused for the `getrandom` dependency.
- There's lots of lots of more unused code that should be deleted.

**Review by LesnyRumcajs — APPROVED** [review]

**Comment by lemmih** [comment]
`Runtime` and `RuntimePolicy` also appear to be unused.

**Comment by lemmih** [comment]
Maybe also the `Verifier` trait along with more traits from the same module.

**Review by lemmih — APPROVED** [review]
Alright! Let's tackle the rest in a separate PR.

**Pull request merged**
