### PR TITLE
feat: expose superset of SectorOnChainInfo fields

### PR DESCRIPTION
**Pull request by lemmih**
**Summary of changes**
Changes introduced in this pull request:
- Expose 4 new fields in `SectorOnChainInfo`.

Note, these fields are the union of fields available through version v9 to v12. The newest actors do not have all of these fields, but we still need to report them.

**Reference issue to close (if applicable)**

Closes 

**Other information and links**

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
@lemmih this `struct` is incorrect.

https://github.com/filecoin-project/builtin-actors/blob/master/actors/miner/src/types.rs#L368-L369

The `simple_qa_power` was replaced by `flags` and thus if we want to have the exact same structure for all versions (which may bite us later), this needs to check for the `SIMPLE_QA_POWER` bit, see:
https://github.com/ChainSafe/forest/blob/main/src/state_migration/type_migrations/miner/sector_onchain_info_v11_to_v12.rs

**Review by hanabi1224 — APPROVED** [review]

**Comment by lemmih** [comment]
> @lemmih this `struct` is incorrect.
> 
> https://github.com/filecoin-project/builtin-actors/blob/master/actors/miner/src/types.rs#L368-L369
> 
> The `simple_qa_power` was replaced by `flags` and thus if we want to have the exact same structure for all versions (which may bite us later), this needs to check for the `SIMPLE_QA_POWER` bit, see: https://github.com/ChainSafe/forest/blob/main/src/state_migration/type_migrations/miner/sector_onchain_info_v11_to_v12.rs

The Lotus RPC API uses the v9 miner struct, and we have to mirror it if we want to be in compliance: https://github.com/filecoin-project/lotus/blob/0b0d7c96df590ab6ac2db3fb975a112a9a220199/chain/actors/builtin/miner/miner.go#L12

I have no idea _why_ Lotus would use the v9 struct in their API, but they do. My thinking is that we have to expose a structure that is a union of all the different versions.

**Comment by lemmih** [comment]
As far as I can tell, Lotus is not checking the `SIMPLE_QA_POWER` flag in the API call for `StateMinerActiveSectors`. Instead, they set the field to `false` for all v12 states. I have no idea why, and it may well be a bug/misfeature. Matching their API means matching their bugs as well.

**Comment by LesnyRumcajs** [comment]
> As far as I can tell, Lotus is not checking the `SIMPLE_QA_POWER` flag in the API call for `StateMinerActiveSectors`. Instead, they set the field to `false` for all v12 states. I have no idea why, and it may well be a bug/misfeature. Matching their API means matching their bugs as well.

Understood. I'll look it up in their code and ask.

**Review by LesnyRumcajs — APPROVED** [review]

**Pull request merged**
